name: couchbase
services:
  db:
    image: couchbase/server:community
    container_name: couchbase
    hostname: couchbase
    restart: always
    pull_policy: always
    stdin_open: true
    tty: true
    environment:
      - COUCHBASE_BUCKET=default
      - COUCHBASE_BUCKET_RAMSIZE=512
      - COUCHBASE_ADMINISTRATOR_USERNAME=${DB_ADMIN_NAME:-root}
      - COUCHBASE_ADMINISTRATOR_PASSWORD=${DB_ADMIN_PASS:-password}
    ports:
      - '11210:11210'
      - '8092-8096:8092-8096'
      - '172.17.0.1:8091:8091'
    volumes:
      - /var/lib/srv/$USER/docker/couchbase/server/community/rootfs/data/db/couchbase:/opt/couchbase/var
    healthcheck:
      test: curl --fail http://localhost:8091/pools || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    extra_hosts:
      - 'localhost:172.17.0.1'
      - 'couchbasedb:host-gateway'
      - 'host.docker.internal:host-gateway'
    networks:
      - couchbase

networks:
  couchbase:
    name: couchbase
    external: false
